const root=document.querySelector('#root');let state,category='全部',query='',banner=0,dirty=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=s=>{const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',3500);};
async function api(url,method='GET',data){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw Error(b.error||'请求失败');return b;}
const header=admin=>`<header><div class="brand"><span>拾</span>拾光软件库</div>${admin?'<a href="/">查看软件库 ↗</a>':''}</header>`;
function home(){root.innerHTML=`<main>${header(false)}<section id="hero"></section><div class="dots" id="dots"></div><div class="notice">◉ 公告 · ${esc(state.announcement||'暂无公告')}</div><div class="toolbar"><div><div class="eyebrow">CURATED FOR YOU</div><h2>发现你的下一个好工具</h2></div><input id="search" placeholder="搜索软件名称或简介" aria-label="搜索软件"></div><div class="chips" id="chips"></div><div class="grid" id="apps"></div><footer>拾光软件库 · 让好软件被看见　<button id="refresh" class="secondary">刷新内容</button></footer></main>`;drawBanner();document.querySelector('#search').oninput=e=>{query=e.target.value;cards();};document.querySelector('#refresh').onclick=loadHome;cards();}
function drawBanner(){const b=state.banners[banner%Math.max(state.banners.length,1)];document.querySelector('#hero').innerHTML=b?`<div class="hero" style="background:${esc(b.color)}"><div class="eyebrow">THE DAILY COLLECTION</div><h1>${esc(b.title)}</h1><p>${esc(b.subtitle)}</p><span class="tag">精选推荐 · 持续更新</span></div>`:'';document.querySelector('#dots').innerHTML=state.banners.map((_,i)=>`<button aria-label="第 ${i+1} 张轮播图" data-banner="${i}" class="${i===banner%state.banners.length?'active':''}"></button>`).join('');document.querySelectorAll('[data-banner]').forEach(b=>b.onclick=()=>{banner=Number(b.dataset.banner);drawBanner();});}
function cards(){const cats=['全部','首页推荐',...new Set(state.apps.map(a=>a.category))];document.querySelector('#chips').innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${category===c?'active':''}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;cards();});const apps=state.apps.filter(a=>(category==='全部'||category==='首页推荐'&&a.featured||a.category===category)&&`${a.name} ${a.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.featured)-Number(a.featured));document.querySelector('#apps').innerHTML=apps.length?apps.map(a=>`<article class="card"><div class="row"><div class="appicon">${esc(a.name[0])}</div>${a.featured?'<span class="tag">编辑推荐</span>':''}</div><h3>${esc(a.name)}</h3><span class="muted">${esc(a.category)} · v${esc(a.version)}</span><p>${esc(a.description.slice(0,60))}</p><button data-detail="${esc(a.id)}">查看详情 ↗</button></article>`).join(''):'<div class="empty">没有找到匹配的软件</div>';document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));}
function detail(id){const a=state.apps.find(a=>a.id===id);const d=document.createElement('dialog');d.innerHTML=`<div class="appicon">${esc(a.name[0])}</div><h2>${esc(a.name)}</h2><div class="muted">${esc(a.category)} · v${esc(a.version)}</div><p style="white-space:pre-wrap">${esc(a.description)}</p><div class="row">${a.downloadUrl?`<a class="button" href="${esc(a.downloadUrl)}" target="_blank" rel="noopener noreferrer">下载安装包 ↗</a>`:'<span class="muted">尚未提供安装包</span>'}<button class="secondary">关闭</button></div>`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
async function loadHome(){try{state=await api('/api/content');home();}catch(e){root.innerHTML=`<main>${header(false)}<p>暂时无法加载内容，请刷新重试。</p></main>`;toast(e.message);}}
function login(){root.innerHTML=`<main>${header(true)}<form class="panel login"><div class="eyebrow">CONTENT STUDIO</div><h1>欢迎回来</h1><p>登录后管理软件与首页内容。</p><label>管理员密码<input type="password" name="password" required autocomplete="current-password"></label><button>登录后台</button></form></main>`;root.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await api('/api/login','POST',{password:new FormData(e.target).get('password')});await loadAdmin();}catch(e){toast(e.message);}};}
const field=(label,key,value,type='text')=>`<label>${label}<input data-key="${key}" type="${type}" value="${esc(value)}" ${key==='name'?'required':''}></label>`;
function admin(){root.innerHTML=`<main>${header(true)}<div class="adminlayout"><aside class="nav"><div class="eyebrow">CONTENT STUDIO</div><h2>内容管理</h2><p>编辑内容后，点击“保存并发布”。用户打开或刷新软件库即可看到更新。</p><p>${state.apps.length} 款软件 · ${state.banners.length} 张轮播图</p><button id="logout" class="secondary">退出登录</button></aside><div><section class="panel"><h2>循环文字内容</h2><textarea id="announcement" maxlength="2000">${esc(state.announcement)}</textarea></section><section class="panel"><div class="row"><h2>首页轮播图</h2><button id="add-banner" class="secondary">＋ 添加</button></div><p class="muted">选择本地图片上传，支持 JPG、PNG、WebP，每张不超过 5 MB。上传后点击保存并发布。</p><div id="banners">${state.banners.map((b,i)=>`<div class="adminapp" data-bi="${i}">${b.image?`<img src="${esc(b.image)}" style="width:100%;max-height:180px;object-fit:contain" alt="轮播预览">`:""}<label>上传轮播图片<input type="file" accept="image/png,image/jpeg,image/webp" data-upload="${i}"></label><button class="danger" data-del-banner="${i}">删除轮播图</button></div>`).join('')}</div></section><section class="panel"><div class="row"><h2>软件管理</h2><button id="add-app" class="secondary">＋ 添加软件</button></div>${state.apps.map((a,i)=>`<div class="adminapp" data-ai="${i}"><div class="fields">${field('软件名称','name',a.name)}${field('分类','category',a.category)}${field('版本','version',a.version)}${field('APK 下载地址（HTTPS）','downloadUrl',a.downloadUrl,'url')}</div><label>软件简介<textarea data-key="description">${esc(a.description)}</textarea></label><div class="row"><label><input type="checkbox" data-key="featured" ${a.featured?'checked':''}>首页推荐</label><label><input type="checkbox" data-key="published" ${a.published?'checked':''}>上架</label><button class="danger" data-del-app="${i}">删除软件</button></div></div>`).join('')}</section><div class="savebar"><span id="save-status">所有修改需要发布后生效</span><button id="save">保存并发布</button></div></div></div></main>`;
 root.onchange=async e=>{if(e.target.dataset.upload===undefined)return;const f=e.target.files[0];if(!f)return;if(f.size>5000000)return toast("图片请小于 5 MB");e.target.disabled=true;try{const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});const result=await api("/api/admin/upload","POST",{image});state.banners[Number(e.target.dataset.upload)].image=result.url;dirty=true;admin();toast("图片已上传，请保存并发布");}catch(err){toast(err.message);e.target.disabled=false;}}; root.oninput=e=>{dirty=true;document.querySelector('#save-status').textContent='有未发布的修改';if(e.target.id==='announcement')state.announcement=e.target.value;const parent=e.target.closest('[data-ai],[data-bi]');if(parent&&e.target.dataset.key){const item=parent.dataset.ai!==undefined?state.apps[Number(parent.dataset.ai)]:state.banners[Number(parent.dataset.bi)];item[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.value;}};
 document.querySelector('#add-app').onclick=()=>{state.apps.push({id:crypto.randomUUID(),name:'新软件',category:'效率工具',version:'1.0.0',description:'',downloadUrl:'',featured:false,published:false});dirty=true;admin();};document.querySelector('#add-banner').onclick=()=>{if(state.banners.length>=8)return toast('最多添加 8 张轮播图');state.banners.push({title:'新的推荐',subtitle:'在这里填写推荐内容',color:'#dcebc9'});dirty=true;admin();};
 document.querySelectorAll('[data-del-app]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这款软件？保存发布后生效。')){state.apps.splice(Number(b.dataset.delApp),1);dirty=true;admin();}});document.querySelectorAll('[data-del-banner]').forEach(b=>b.onclick=()=>{state.banners.splice(Number(b.dataset.delBanner),1);dirty=true;admin();});
 document.querySelector('#save').onclick=async()=>{const b=document.querySelector('#save');b.disabled=true;try{state=await api('/api/admin/content','PUT',state);dirty=false;admin();toast('已发布，安卓端刷新后即可看到');}catch(e){toast(e.message);b.disabled=false;}};document.querySelector('#logout').onclick=async()=>{if(dirty&&!confirm('放弃尚未发布的修改并退出？'))return;await api('/api/admin/logout','POST');dirty=false;root.oninput=null;login();};}
const baseAdmin=admin;
admin=function(){
 baseAdmin();
 state.settings||={bannerInterval:4000,tickerSpeed:12};
 state.notices.forEach(n=>{n.pinned=Boolean(n.pinned);});
 const panel=document.createElement('section');panel.className='panel';
 panel.innerHTML=`<h2>轮播与文字设置</h2><div class="fields"><label>自动轮播间隔（秒）<input id="banner-interval" type="number" min="1" max="60" step="1" value="${state.settings.bannerInterval/1000}"></label><label>循环文字速度（秒）<input id="ticker-speed" type="number" min="3" max="120" step="1" value="${state.settings.tickerSpeed}"></label></div><p class="muted">轮播间隔越小切换越快；文字秒数越小滚动越快。</p><h2>公告专区</h2><div id="notice-fields">${state.notices.map((n,i)=>`<div class="adminapp" data-notice="${i}">${field('标题','title',n.title)}${field('内容','text',n.text)}${field('按钮名称','button',n.button)}${n.image?`<img class="admin-icon-preview" src="${esc(n.image)}" alt="公告图标预览">`:''}<label>上传公告图标<input data-notice-image="${i}" type="file" accept="image/png,image/jpeg,image/webp"></label>${field('按钮链接（可空）','url',n.url)}<label><input data-key="pinned" type="checkbox" ${n.pinned?'checked':''}>置顶此公告</label><button data-remove-notice="${i}" class="secondary">删除公告</button></div>`).join('')}</div><button id="add-notice" class="secondary">＋ 添加公告</button><h2>分享按钮</h2><div data-share>${field('按钮文字','label',state.share.label)}${field('分享标题','title',state.share.title)}${field('分享内容','text',state.share.text)}${field('分享网址（留空使用当前地址）','url',state.share.url)}</div><h2>网页工具</h2><div id="tool-fields">${state.tools.map((t,i)=>`<div class="adminapp" data-tool="${i}">${field('按钮名称','name',t.name)}${field('说明','description',t.description)}${field('网页地址','url',t.url)}<label><input data-key="published" type="checkbox" ${t.published?'checked':''}>显示此工具</label><button data-remove-tool="${i}" class="secondary">删除</button></div>`).join('')}</div><button id="add-tool" class="secondary">＋ 添加网页工具</button>`;
 document.querySelector('.savebar').before(panel);
 panel.oninput=e=>{e.stopPropagation();const key=e.target.dataset.key;if(e.target.id==='banner-interval')state.settings.bannerInterval=Number(e.target.value)*1000;else if(e.target.id==='ticker-speed')state.settings.tickerSpeed=Number(e.target.value);else if(key){const notice=e.target.closest('[data-notice]'),tool=e.target.closest('[data-tool]'),item=notice?state.notices[Number(notice.dataset.notice)]:tool?state.tools[Number(tool.dataset.tool)]:state.share;item[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;}else return;dirty=true;document.querySelector('#save-status').textContent='有未发布的修改';};
 panel.querySelector('#add-notice').onclick=()=>{state.notices.push({title:'新公告',text:'填写公告内容',button:'查看详情',icon:'📄',url:'',pinned:false});dirty=true;admin();};
 panel.querySelectorAll('[data-remove-notice]').forEach(b=>b.onclick=()=>{state.notices.splice(Number(b.dataset.removeNotice),1);dirty=true;admin();});
 panel.querySelector('#add-tool').onclick=()=>{state.tools.push({name:'新工具',description:'',url:'https://',published:true});dirty=true;admin();};
 panel.querySelectorAll('[data-remove-tool]').forEach(b=>b.onclick=()=>{state.tools.splice(Number(b.dataset.removeTool),1);dirty=true;admin();});
};
const contentAdmin=admin;
async function uploadIcon(file){
 if(!file) return null;
 if(file.size>5000000)throw Error('图片请小于 5 MB');
 const image=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});
 return (await api('/api/admin/upload','POST',{image})).url;
}
admin=function(){
 contentAdmin();state.categories||=[];
 const mark=()=>{dirty=true;document.querySelector('#save-status').textContent='有未发布的修改';};
 document.querySelectorAll('[data-notice-image]').forEach(input=>input.onchange=async e=>{
  e.stopPropagation();const file=input.files[0];if(!file)return;input.disabled=true;
  try{state.notices[Number(input.dataset.noticeImage)].image=await uploadIcon(file);mark();admin();toast('图标已上传，请保存并发布');}catch(error){toast(error.message);input.disabled=false;}
 });
 const panel=document.createElement('section');panel.className='panel';panel.id='category-admin';
 panel.innerHTML='<h2>软件分类管理</h2><p class="muted">分类以卡片显示，用户进入分类后可搜索其中的软件。新增软件时选择对应分类。</p>'+state.categories.map((g,i)=>'<div class="adminapp" data-category-index="'+i+'">'+field('分类名称','name',g.name)+field('分类介绍','description',g.description)+(g.image?'<img class="admin-icon-preview" src="'+esc(g.image)+'" alt="分类图标预览">':'')+'<label>分类图片<input type="file" data-category-image="'+i+'" accept="image/png,image/jpeg,image/webp"></label><button type="button" class="secondary" data-delete-category="'+i+'">删除分类</button></div>').join('')+'<button id="add-category" class="secondary">＋ 添加分类</button>';
 document.querySelector('#add-app').closest('.panel').before(panel);
 panel.oninput=e=>{
  e.stopPropagation();const group=e.target.closest('[data-category-index]'),key=e.target.dataset.key;if(!group||!key)return;
  const g=state.categories[Number(group.dataset.categoryIndex)],previous=g.name;g[key]=e.target.value;
  if(key==='name')state.apps.forEach(a=>{if(a.category===previous)a.category=g.name;});
  mark();
 };
 panel.onchange=async e=>{
  e.stopPropagation();if(e.target.dataset.categoryImage===undefined)return;const input=e.target,file=input.files[0];if(!file)return;input.disabled=true;
  try{state.categories[Number(input.dataset.categoryImage)].image=await uploadIcon(file);mark();admin();toast('分类图片已上传，请保存并发布');}catch(error){toast(error.message);input.disabled=false;}
 };
 panel.querySelector('#add-category').onclick=()=>{let name='新分类',i=2;while(state.categories.some(g=>g.name===name))name='新分类 '+i++;state.categories.push({name,description:'',image:''});mark();admin();};
 panel.querySelectorAll('[data-delete-category]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.deleteCategory);if(state.apps.some(a=>a.category===state.categories[i].name))return toast('请先将该分类的软件移至其他分类');state.categories.splice(i,1);mark();admin();});
 const options=document.createElement('datalist');options.id='software-categories';options.innerHTML=state.categories.map(g=>'<option value="'+esc(g.name)+'"></option>').join('');panel.append(options);
 document.querySelectorAll('[data-ai] input[data-key="category"]').forEach(input=>input.setAttribute('list','software-categories'));
};
async function loadAdmin(){try{state=await api('/api/admin/content');admin();}catch{login();}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(location.pathname==='/admin')loadAdmin();else import('/mobile.js');
