const root=document.querySelector('#root');let state,category='全部',query='',banner=0,dirty=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=s=>{const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',3500);};
async function api(url,method='GET',data){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw Error(b.error||'请求失败');return b;}
const header=admin=>`<header><div class="brand"><span>拾</span>拾光软件库</div><a href="${admin?'/':'/admin'}">${admin?'查看软件库 ↗':'管理后台 ↗'}</a></header>`;
function home(){root.innerHTML=`<main>${header(false)}<section id="hero"></section><div class="dots" id="dots"></div><div class="notice">◉ 公告 · ${esc(state.announcement||'暂无公告')}</div><div class="toolbar"><div><div class="eyebrow">CURATED FOR YOU</div><h2>发现你的下一个好工具</h2></div><input id="search" placeholder="搜索软件名称或简介" aria-label="搜索软件"></div><div class="chips" id="chips"></div><div class="grid" id="apps"></div><footer>拾光软件库 · 让好软件被看见　<button id="refresh" class="secondary">刷新内容</button></footer></main>`;drawBanner();document.querySelector('#search').oninput=e=>{query=e.target.value;cards();};document.querySelector('#refresh').onclick=loadHome;cards();}
function drawBanner(){const b=state.banners[banner%Math.max(state.banners.length,1)];document.querySelector('#hero').innerHTML=b?`<div class="hero" style="background:${esc(b.color)}"><div class="eyebrow">THE DAILY COLLECTION</div><h1>${esc(b.title)}</h1><p>${esc(b.subtitle)}</p><span class="tag">精选推荐 · 持续更新</span></div>`:'';document.querySelector('#dots').innerHTML=state.banners.map((_,i)=>`<button aria-label="第 ${i+1} 张轮播图" data-banner="${i}" class="${i===banner%state.banners.length?'active':''}"></button>`).join('');document.querySelectorAll('[data-banner]').forEach(b=>b.onclick=()=>{banner=Number(b.dataset.banner);drawBanner();});}
function cards(){const cats=['全部','首页推荐',...new Set(state.apps.map(a=>a.category))];document.querySelector('#chips').innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${category===c?'active':''}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;cards();});const apps=state.apps.filter(a=>(category==='全部'||category==='首页推荐'&&a.featured||a.category===category)&&`${a.name} ${a.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(b.featured)-Number(a.featured));document.querySelector('#apps').innerHTML=apps.length?apps.map(a=>`<article class="card"><div class="row"><div class="appicon">${esc(a.name[0])}</div>${a.featured?'<span class="tag">编辑推荐</span>':''}</div><h3>${esc(a.name)}</h3><span class="muted">${esc(a.category)} · v${esc(a.version)}</span><p>${esc(a.description.slice(0,60))}</p><button data-detail="${esc(a.id)}">查看详情 ↗</button></article>`).join(''):'<div class="empty">没有找到匹配的软件</div>';document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>detail(b.dataset.detail));}
function detail(id){const a=state.apps.find(a=>a.id===id);const d=document.createElement('dialog');d.innerHTML=`<div class="appicon">${esc(a.name[0])}</div><h2>${esc(a.name)}</h2><div class="muted">${esc(a.category)} · v${esc(a.version)}</div><p style="white-space:pre-wrap">${esc(a.description)}</p><div class="row">${a.downloadUrl?`<a class="button" href="${esc(a.downloadUrl)}" target="_blank" rel="noopener noreferrer">下载安装包 ↗</a>`:'<span class="muted">尚未提供安装包</span>'}<button class="secondary">关闭</button></div>`;document.body.append(d);d.querySelector('button').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();}
async function loadHome(){try{state=await api('/api/content');home();}catch(e){root.innerHTML=`<main>${header(false)}<p>暂时无法加载内容，请刷新重试。</p></main>`;toast(e.message);}}
function login(){root.innerHTML=`<main>${header(true)}<form class="panel login"><div class="eyebrow">CONTENT STUDIO</div><h1>欢迎回来</h1><p>登录后管理软件与首页内容。</p><label>管理员密码<input type="password" name="password" required autocomplete="current-password"></label><button>登录后台</button></form></main>`;root.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await api('/api/login','POST',{password:new FormData(e.target).get('password')});await loadAdmin();}catch(e){toast(e.message);}};}
const field=(label,key,value,type='text')=>`<label>${label}<input data-key="${key}" type="${type}" value="${esc(value)}" ${key==='name'?'required':''}></label>`;
function admin(){root.innerHTML=`<main>${header(true)}<div class="adminlayout"><aside class="nav"><div class="eyebrow">CONTENT STUDIO</div><h2>内容管理</h2><p>编辑内容后，点击“保存并发布”。用户打开或刷新软件库即可看到更新。</p><p>${state.apps.length} 款软件 · ${state.banners.length} 张轮播图</p><button id="logout" class="secondary">退出登录</button></aside><div><section class="panel"><h2>首页公告</h2><textarea id="announcement" maxlength="2000">${esc(state.announcement)}</textarea></section><section class="panel"><div class="row"><h2>首页轮播图</h2><button id="add-banner" class="secondary">＋ 添加</button></div><p class="muted">首版提供可修改文字和底色的轮播卡片，最多 8 张。</p><div id="banners">${state.banners.map((b,i)=>`<div class="adminapp" data-bi="${i}">${field('标题','title',b.title)}${field('说明','subtitle',b.subtitle)}${field('背景颜色','color',b.color,'color')}<button class="danger" data-del-banner="${i}">删除轮播图</button></div>`).join('')}</div></section><section class="panel"><div class="row"><h2>软件管理</h2><button id="add-app" class="secondary">＋ 添加软件</button></div>${state.apps.map((a,i)=>`<div class="adminapp" data-ai="${i}"><div class="fields">${field('软件名称','name',a.name)}${field('分类','category',a.category)}${field('版本','version',a.version)}${field('APK 下载地址（HTTPS）','downloadUrl',a.downloadUrl,'url')}</div><label>软件简介<textarea data-key="description">${esc(a.description)}</textarea></label><div class="row"><label><input type="checkbox" data-key="featured" ${a.featured?'checked':''}>首页推荐</label><label><input type="checkbox" data-key="published" ${a.published?'checked':''}>上架</label><button class="danger" data-del-app="${i}">删除软件</button></div></div>`).join('')}</section><div class="savebar"><span id="save-status">所有修改需要发布后生效</span><button id="save">保存并发布</button></div></div></div></main>`;
 root.oninput=e=>{dirty=true;document.querySelector('#save-status').textContent='有未发布的修改';if(e.target.id==='announcement')state.announcement=e.target.value;const parent=e.target.closest('[data-ai],[data-bi]');if(parent&&e.target.dataset.key){const item=parent.dataset.ai!==undefined?state.apps[Number(parent.dataset.ai)]:state.banners[Number(parent.dataset.bi)];item[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.value;}};
 document.querySelector('#add-app').onclick=()=>{state.apps.push({id:crypto.randomUUID(),name:'新软件',category:'效率工具',version:'1.0.0',description:'',downloadUrl:'',featured:false,published:false});dirty=true;admin();};document.querySelector('#add-banner').onclick=()=>{if(state.banners.length>=8)return toast('最多添加 8 张轮播图');state.banners.push({title:'新的推荐',subtitle:'在这里填写推荐内容',color:'#dcebc9'});dirty=true;admin();};
 document.querySelectorAll('[data-del-app]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这款软件？保存发布后生效。')){state.apps.splice(Number(b.dataset.delApp),1);dirty=true;admin();}});document.querySelectorAll('[data-del-banner]').forEach(b=>b.onclick=()=>{state.banners.splice(Number(b.dataset.delBanner),1);dirty=true;admin();});
 document.querySelector('#save').onclick=async()=>{const b=document.querySelector('#save');b.disabled=true;try{state=await api('/api/admin/content','PUT',state);dirty=false;admin();toast('已发布，安卓端刷新后即可看到');}catch(e){toast(e.message);b.disabled=false;}};document.querySelector('#logout').onclick=async()=>{if(dirty&&!confirm('放弃尚未发布的修改并退出？'))return;await api('/api/admin/logout','POST');dirty=false;root.oninput=null;login();};}
async function loadAdmin(){try{state=await api('/api/admin/content');admin();}catch{login();}}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(location.pathname==='/admin')loadAdmin();else{loadHome();setInterval(()=>{if(state&&state.banners.length>1){banner++;drawBanner();}},5000);}
