const root=document.querySelector('#root');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',apps:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',tools:'m14 6 4-4 4 4-4 4M15 9 4 20l-3-3L12 6',me:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM4 22v-3a8 8 0 0 1 16 0v3',arrow:'M5 12h14m-6-6 6 6-6 6',share:'M12 16V2m-5 5 5-5 5 5M4 12v9h16v-9'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.arrow}"/></svg>`;
let content,user=null,tab='home',q='',cat='全部',register=false;
async function api(url,method='GET',data){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});const b=await r.json();if(!r.ok)throw Error(b.error||'请求失败');return b;}
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display='none',3200);}
function dialog(html){const d=document.createElement('dialog');d.innerHTML=html+'<button class="secondary close-dialog">关闭</button>';document.body.append(d);d.querySelector('.close-dialog').onclick=()=>d.close();d.onclose=()=>d.remove();d.showModal();return d;}
async function share(){const s=content.share;const data={title:s.title,text:s.text,url:s.url||location.origin};try{if(navigator.share){await navigator.share(data);return;}await navigator.clipboard.writeText(`${data.title}\n${data.text}\n${data.url}`);toast('分享内容已复制');}catch(e){if(e.name!=='AbortError')dialog(`<h2>${esc(s.title)}</h2><textarea readonly>${esc(`${s.text}\n${s.url||location.origin}`)}</textarea><p>长按或选中文字即可复制分享。</p>`);}}
function render(){disposeHome();document.body.classList.add('mobile-ui');root.innerHTML=`<main class="phone"><section class="screen" id="screen"></section><nav class="mobile-nav" aria-label="底部导航">${[['home','首页'],['apps','软件'],['tools','工具'],['me','我的']].map(([id,name])=>`<a href="#${id}" class="${tab===id?'selected':''}" ${tab===id?'aria-current="page"':''}>${icon(id)}<span>${name}</span></a>`).join('')}</nav></main>`;const screen=document.querySelector('#screen');if(tab==='home'){const banners=content.banners.filter(b=>b.image);screen.innerHTML=`<button class="share-button" id="share">${icon('share')}<span>${esc(content.share.label)}</span>${icon('arrow')}</button><div class="carousel-block" id="carousel">${banners.map((b,i)=>`<img class="banner-image" src="${esc(b.image)}" alt="轮播图 ${i+1}">`).join('')}</div>${banners.length>1?`<div class="carousel-dots">${banners.map((_,i)=>`<i class="${i===0?'active':''}"></i>`).join('')}</div>`:''}<div class="ticker"><span style="animation-duration:${Math.max(3,Number(content.settings?.tickerSpeed||12))}s">${esc(content.announcement||'欢迎来到软件库')}</span></div><section class="notice-section"><h2>【公告专区】</h2><div class="notice-grid">${content.notices.slice().sort((a,b)=>Number(b.pinned)-Number(a.pinned)).map(n=>`<article class="notice-card">${n.pinned?'<b class="pin">置顶</b>':''}<div class="notice-icon">${n.image?`<img src="${esc(n.image)}" alt="">`:esc(n.icon)}</div><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${n.url?`<a class="notice-link" href="${esc(n.url)}" target="_blank" rel="noopener">${esc(n.button)} &gt;</a>`:`<button class="notice-link" data-notice-detail="${content.notices.indexOf(n)}">${esc(n.button)} &gt;</button>`}</article>`).join('')}</div></section><button class="text-button" id="refresh">刷新内容 ↻</button>`;screen.querySelector('#share').onclick=share;screen.querySelector('#refresh').onclick=load;setupHome(screen);}else if(tab==='apps'){renderRepository();}else if(tab==='tools'){screen.innerHTML=`<div class="kicker">THE TOOLBOX / 工具</div><h1>轻点，即刻打开。</h1><p>常用的网页工具，放在触手可及的地方。</p><div class="tool-grid">${content.tools.length?content.tools.map((t,i)=>`<a class="tool-card" href="${esc(t.url)}" target="_blank" rel="noopener noreferrer"><div class="row"><span class="index">${String(i+1).padStart(2,'0')}</span>${icon('arrow')}</div><h2>${esc(t.name)}</h2><p>${esc(t.description)}</p><span class="mono">打开网页 ↗</span></a>`).join(''):'<div class="empty">工具箱正在整理中，敬请期待。</div>'}</div>`;}else me();}
function renderRepository(){
 const screen=document.querySelector('#screen');
 const selected=location.hash.startsWith('#apps/')?decodeURIComponent(location.hash.slice(6)):null;
 if(selected===null){
  const groups=[...(content.categories||[])];
  for(const a of content.apps)if(!groups.some(g=>g.name===a.category))groups.push({name:a.category,description:'',image:''});
  screen.innerHTML='<h1 class="page-title">软件仓库</h1><p>选择分类，发现你需要的软件。</p><div class="notice-grid category-grid">'+groups.map((g,i)=>'<a class="notice-card category-card" href="#apps/'+encodeURIComponent(g.name)+'">'+(g.image?'<img class="category-image" src="'+esc(g.image)+'" alt="">':'<span class="category-symbol">'+icon('apps')+'</span>')+'<h3>'+esc(g.name)+'</h3><p>'+esc(g.description||'浏览此分类的软件')+'</p><span class="notice-link">'+content.apps.filter(a=>a.category===g.name).length+' 款软件 &gt;</span></a>').join('')+'</div>';
  return;
 }
 q='';cat=selected;
 screen.innerHTML='<a class="back-categories" href="#apps">← 全部分类</a><h1 class="page-title">'+esc(selected)+'</h1><input class="search" id="search" aria-label="搜索当前分类的软件" placeholder="搜索本分类的软件名称、简介…"><div id="list"></div>';
 screen.querySelector('#search').oninput=e=>{q=e.target.value;list();};list();
}
function list(){
 const apps=content.apps.filter(a=>a.category===cat&&(`${a.name} ${a.description}`).toLowerCase().includes(q.toLowerCase()));
 document.querySelector('#list').innerHTML=apps.length?apps.map(a=>'<button class="software" data-app="'+esc(a.id)+'"><span class="software-icon">'+esc(a.name[0])+'</span><span class="software-copy"><strong>'+esc(a.name)+'</strong><small>'+esc(a.version)+'</small><span>'+esc(a.description)+'</span></span>'+icon('arrow')+'</button>').join(''):'<div class="empty">本分类没有找到匹配的软件</div>';
 document.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>{const a=content.apps.find(a=>a.id===b.dataset.app);dialog('<h2>'+esc(a.name)+'</h2><p class="notice-text">'+esc(a.description)+'</p>'+(a.downloadUrl?'<a class="button" href="'+esc(a.downloadUrl)+'" target="_blank" rel="noopener">下载安装包 ↗</a>':'<p>暂未提供下载地址</p>'));});
}

function me(){const screen=document.querySelector('#screen');screen.innerHTML=`<div class="kicker">YOUR SPACE / 我的</div>${user?`<div class="profile-avatar">${esc(user.username[0])}</div><h1>你好，${esc(user.username)}。</h1><p>欢迎回到你的软件空间。</p><div class="profile-line"><span>账号</span><strong>${esc(user.username)}</strong></div><div class="profile-line"><span>加入时间</span><strong>${esc(user.createdAt.slice(0,10))}</strong></div><button id="logout-user" class="share-button">退出登录 ${icon('arrow')}</button>`:`<h1>${register?'从这里，开始。':'欢迎回来。'}</h1><p>${register?'创建账号，开启你的软件空间。':'登录账号，继续探索好用的软件。'}</p><div class="auth-tabs"><button id="login-tab" class="${!register?'active':''}">登录</button><button id="register-tab" class="${register?'active':''}">注册</button></div><form id="user-form"><label>用户名<input name="username" autocomplete="username" minlength="3" maxlength="24" required placeholder="3–24 位字母、数字或中文"></label><label>密码<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="8" maxlength="128" required placeholder="至少 8 位"></label>${register?'<label>确认密码<input name="confirm" type="password" autocomplete="new-password" required placeholder="再输入一次密码"></label>':''}<p id="auth-error" role="alert"></p><button class="share-button" type="submit">${register?'创建账号':'登录'} ${icon('arrow')}</button></form>`}`;if(user){screen.querySelector('#logout-user').onclick=async()=>{try{await api('/api/user/logout','POST');user=null;me();}catch(e){toast(e.message);}};return;}screen.querySelector('#login-tab').onclick=()=>{register=false;me();};screen.querySelector('#register-tab').onclick=()=>{register=true;me();};screen.querySelector('#user-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);const error=document.querySelector('#auth-error');if(register&&form.get('password')!==form.get('confirm')){error.textContent='两次输入的密码不一致';return;}const button=e.target.querySelector('[type=submit]');button.disabled=true;try{const b=await api(`/api/user/${register?'register':'login'}`,'POST',{username:form.get('username'),password:form.get('password')});user=b.user;me();toast(register?'注册成功，已登录':'登录成功');}catch(e){error.textContent=e.message;button.disabled=false;}};}
function route(){tab=location.hash.startsWith('#apps/')?'apps':['home','apps','tools','me'].includes(location.hash.slice(1))?location.hash.slice(1):'home';if(content)render();window.scrollTo(0,0);}
async function load(){try{content=await api('/api/content');route();}catch(e){root.innerHTML='<main class="phone"><h1>暂时无法连接</h1><p>请检查网络后重试。</p><button id="retry">重新加载</button></main>';document.querySelector('#retry').onclick=load;}}
let disposeHome=()=>{};
function setupHome(screen){
 const carousel=screen.querySelector('#carousel'),slides=[...carousel.querySelectorAll('img')],dots=[...screen.querySelectorAll('.carousel-dots i')];
 const interval=Math.max(1000,Number(content.settings?.bannerInterval)||4000);
 let timer,index=0,pointer=null,moved=false;
 const stop=()=>clearTimeout(timer);
 const nearest=()=>Math.max(0,Math.min(slides.length-1,Math.round(carousel.scrollLeft/Math.max(1,carousel.clientWidth))));
 const show=i=>{index=(i+slides.length)%slides.length;carousel.scrollTo({left:index*carousel.clientWidth,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});};
 const schedule=()=>{stop();if(slides.length>1&&!document.hidden&&!pointer)timer=setTimeout(()=>{show(nearest()+1);schedule();},interval);};
 carousel.addEventListener('scroll',()=>{index=nearest();dots.forEach((d,i)=>d.classList.toggle('active',i===index));},{passive:true});
 carousel.addEventListener('pointerdown',e=>{if(slides.length<2||e.button!==0)return;stop();pointer={id:e.pointerId,x:e.clientX,left:carousel.scrollLeft};moved=false;carousel.setPointerCapture(e.pointerId);carousel.classList.add('dragging');});
 carousel.addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const delta=e.clientX-pointer.x;if(Math.abs(delta)>8)moved=true;if(moved){e.preventDefault();carousel.scrollLeft=pointer.left-delta;}});
 const finish=e=>{if(!pointer||pointer.id!==e.pointerId)return;const delta=e.clientX-pointer.x;const initial=Math.round(pointer.left/Math.max(1,carousel.clientWidth));pointer=null;carousel.classList.remove('dragging');if(carousel.hasPointerCapture(e.pointerId))carousel.releasePointerCapture(e.pointerId);show(Math.abs(delta)>35?initial+(delta<0?1:-1):nearest());schedule();};
 carousel.addEventListener('pointerup',finish);
 carousel.addEventListener('pointercancel',()=>{pointer=null;carousel.classList.remove('dragging');schedule();});
 carousel.addEventListener('dragstart',e=>e.preventDefault());
 carousel.tabIndex=0;carousel.setAttribute('aria-label','轮播图片，可左右滑动');
 carousel.addEventListener('keydown',e=>{if(slides.length>1&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();show(nearest()+(e.key==='ArrowRight'?1:-1));schedule();}});
 dots.forEach((d,i)=>{d.setAttribute('role','button');d.tabIndex=0;d.setAttribute('aria-label','切换到第 '+(i+1)+' 张');d.onclick=()=>{show(i);schedule();};d.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')d.click();};});
 const visible=()=>document.hidden?stop():schedule();document.addEventListener('visibilitychange',visible);
 const resize=()=>{carousel.scrollTo({left:index*carousel.clientWidth,behavior:'instant'});};
 window.addEventListener('resize',resize);
 screen.querySelectorAll('[data-notice-detail]').forEach(b=>b.onclick=()=>{const n=content.notices[Number(b.dataset.noticeDetail)];dialog('<h2>'+esc(n.icon)+' '+esc(n.title)+'</h2><p class="notice-text">'+esc(n.text)+'</p>');});
 schedule();disposeHome=()=>{stop();document.removeEventListener('visibilitychange',visible);window.removeEventListener('resize',resize);};
}
window.addEventListener('hashchange',route);
try{user=(await api('/api/user/me')).user;}catch{}
await load();
